on: [push]

name: CI

jobs:
  make_charts:
    name: Make charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install vl-convert
      - run: npm ci
      - run: node ./index.mjs
